### ISSUE TITLE
Automatic Low Detail turns off after starting CoX raid

### ISSUE THREAD

**Issue by bepzi** [bepzi/runelite-plugins#4]
> hi @bepzi I'm not seeing this as fixed - I just downloaded the plugin from the hub, it seems to make the cox lobby low detail but once I enter the raid it's not anymore
>
> It seems to look "ok" and then reverts to high detail after starting the raid.

_Originally posted by @hjdarnel in https://github.com/bepzi/runelite-plugins/issues/2#issuecomment-1965748161_

**Comment by hjdarnel** [comment]
awesome! cheers 😄

**Comment by hjdarnel** [comment]
Think you can submit an update at https://github.com/runelite/plugin-hub/pulls?

**Comment by bepzi** [comment]
@hjdarnel Yep, should be solved once https://github.com/runelite/plugin-hub/pull/5653 is merged
