### ISSUE TITLE
Plugin breaks core CoX plugin again

### ISSUE THREAD

**Issue by YvesW** [bepzi/runelite-plugins#5]
https://discord.com/channels/301497432909414422/301497432909414422/1233794163082788984
https://discord.com/channels/301497432909414422/442492468307427330/1206980249318064219
https://discord.com/channels/301497432909414422/419891709883973642/1204889631779454976

**Comment by bepzi** [comment]
The linked Discord threads are for Low Detail Chambers, not Automatic Low Detail. Automatic Low Detail should not still have this issue, but Low Detail Chambers has been broken for some time now (cc @JacobLindelof)

**Comment by YvesW** [comment]
Gosh darnit, I clearly clicked on the wrong link. Apologies.
